inventory/dashboard/__init__.py
# Comment

inventory/dashboard/routes.py
from flask import render_template, redirect,url_for, request, Blueprint
from inventory import db
from inventory.models import Product, Movement


dashboard_bp = Blueprint('dashboard_bp', __name__)

# Dashboard
@dashboard_bp.route('/')
@dashboard_bp.route("/dashboard")
def dashboard():
    movements = db.session.query(Movement.to_location, Movement.product_id).filter(Movement.from_location=="").distinct(Movement.to_location).all()
    product = Product.query
    qty = Movement.query
    return render_template('dashboard.html', title='Dashboard', movements=movements, qty=qty, product=product)

@dashboard_bp.route('/search_dashboard')
def search_dashboard():
    
    q = request.args.get('query')
    movements = []
    if not q:
        return dashboard()
    product = Product.query.filter(Product.product_name.contains(q)).all()
    lists = db.session.query(Movement.to_location, Movement.product_id).filter(Movement.from_location=="").distinct(Movement.to_location).all()
    for i in lists:
        if q.lower() in i[0].lower():
            movements.append(i)
    if product:
        for p in product:
            for i in lists:
                if(p.product_id == i[1]):
                    movements.append(i)
    product = Product.query
    qty = Movement.query
    movements = list(dict.fromkeys(movements))
    return render_template('dashboard.html', title='Dashboard', movements=movements, qty=qty, product=product, label='Search Dashboard')

inventory/locations/__init__.py
#Comment

inventory/locations/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from inventory import db
from inventory.locations.forms import LocationForm, UpdateLocationForm
from inventory.models import Location
from inventory.utils import save_picture

locations_bp = Blueprint('locations_bp', __name__)


# Location
@locations_bp.route('/search_location')
def search_location():
    query = request.args.get('query')
    if not query:
        return locations()
    else:
        searched_locations = Location.query.filter(Location.location_name.contains(query)).all()
    return render_template('locations.html', locations=searched_locations, title='Search Result', label='Location')

@locations_bp.route('/locations', methods=['GET'])
def locations():
    locations = Location.query.order_by(Location.location_name).all()
    return render_template('locations.html', locations=locations, title='Location', label='Add Location')

@locations_bp.route('/locations/new', methods=['GET', 'POST'])
def new_location():
    form = LocationForm()
    if form.validate_on_submit():
        if form.location_picture.data:
            picture_file = save_picture(form.location_picture.data)
        else:
            picture_file = 'thumbnail-default.jpg'
        location = Location(location_name=form.location_name.data, location_description=form.location_description.data, location_image_file=picture_file)
        db.session.add(location)
        db.session.commit()
        flash('Your location is successfully added in the location list!', 'green')
        return redirect(url_for('locations_bp.locations'))
    return render_template('create_location.html', form=form, title='Add New Location', label='Location')

@locations_bp.route("/location/<int:location_id>")
def location(location_id):
    location = Location.query.get_or_404(location_id)
    return render_template('location.html', title='Update Location', location=location, label='Location')

@locations_bp.route("/location/<int:location_id>/update", methods=['GET', 'POST'])
def update_location(location_id):
    location = Location.query.get_or_404(location_id)
    form = UpdateLocationForm()

    if not location.location_name == form.location_name.data:
        form = LocationForm()

    if form.validate_on_submit():
        if form.location_picture.data:
            print(form.location_picture.data)
            picture_file = save_picture(form.location_picture.data)
            location.location_image_file = picture_file
        location.location_description = form.location_description.data
        location.location_name = form.location_name.data
        db.session.commit()
        flash('Your location has been updated!', 'green')
        return redirect(url_for('locations_bp.location', location_id=location.location_id))
    elif request.method == 'GET':
        form.location_name.data = location.location_name
        form.location_description.data = location.location_description
    form.submit.label.text = 'Update Location'
    return render_template('create_location.html', title='Update Location', form=form, label='Location') 

inventory/movements/__init__.py
#Comment

inventory/movements/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from inventory import db
from inventory.movements.forms import MovementForm
from inventory.models import Product, Location, Movement, StaticMovement
from datetime import datetime
from pytz import timezone

movements_bp = Blueprint('movements_bp', __name__)

def get_choices(form):
    location_choices = [(0, "---")]+[(location.location_id, location.location_name) for location in Location.query.all()]
    form.from_location.choices = location_choices
    form.to_location.choices = location_choices
    form.product_id.choices = [(product.product_id, product.product_name) for product in Product.query.all()]

def convert_location_id_to_name(id):
    if id: return Location.query.filter_by(location_id=id).first().location_name
    elif not id or id == 0: return ""

def convert_location_name_to_id(name):
    if name: return Location.query.filter_by(location_name=name).first().location_id
    else: return 0

def movement_exist(product_id, from_location, to_location):
    return Movement.query.filter_by(from_location=from_location, to_location=to_location, product_id=product_id).first()

def error_conditions(from_location, to_location, qty, existing_prd_in_from_location, existing_prd_in_to_location, check, update_qty):
    #Do not allow to create movement without location in either location field
    if from_location == "" and to_location == "":
        flash('Atleast one location is need', 'red')
    
    #to_location and from_location cannot be same
    elif from_location == to_location:
        flash('Cannot transfer in same location, please select different location', 'red')

    #check if from_location has enough quantity
    elif check == 'new' and existing_prd_in_from_location and ((existing_prd_in_from_location.qty - qty) < 0):
        flash('The quantity of product available in '+ from_location+' is '+ str(existing_prd_in_from_location.qty) + ' which is less than you need', 'red')
    
    #check if from_location exist or not
    elif check == 'new' and not existing_prd_in_from_location and from_location != '':
        flash('The product is not available in '+ from_location + ' location', 'red')
    
    #check if from_location has enough quantity
    elif check == 'update' and existing_prd_in_from_location and ((existing_prd_in_from_location.qty - qty + update_qty) < 0):
        flash('The quantity of product is not available in '+ from_location, 'red')

    #In from location product is not available so throw an error.
    elif (existing_prd_in_to_location and (from_location != "" and to_location != "" and not existing_prd_in_to_location) or to_location == "") and not existing_prd_in_from_location:
        flash('The product is not available in '+ from_location +' location', 'red')

    #Storage Capacity Error
    elif qty > 100 or (existing_prd_in_to_location and existing_prd_in_to_location.qty + qty - update_qty > 100):
        flash('The quantity of product exceeds the storage capacity(100) of '+to_location+' location. You can only move '+str(100-existing_prd_in_to_location.qty) + ' products.', 'red')

    else:
        return 'No error'

def date_convertion():
    now_utc = datetime.now(timezone('UTC'))
    now_asia = now_utc.astimezone(timezone('Asia/Kolkata'))
    return now_asia


@movements_bp.route('/search_movement')
def search_movement():
    query = request.args.get('query')
    if not query:
        return movements()
    product = Product.query.filter(Product.product_name.contains(query)).all()
    from_location = []
    to_location = []
    searched_movements = []
    searched_movements = StaticMovement.query.filter(StaticMovement.from_location.contains(query)).all()
    searched_movements = searched_movements + StaticMovement.query.filter(StaticMovement.to_location.contains(query)).all()
    if product:
        for p in product:
            searched_movements = searched_movements + StaticMovement.query.filter(StaticMovement.product_id==p.product_id).all()
    products = Product.query
    locations = Location.query
    searched_movements = list(dict.fromkeys(searched_movements))
    return render_template('movements.html', movements=searched_movements, title='Search Result', products=products, locations=locations, label='Movement')

@movements_bp.route("/movements")
def movements():
    movements = StaticMovement.query.order_by(StaticMovement.timestamp.desc()).all()
    products = Product.query
    locations = Location.query
    return render_template('movements.html', title='Movement',movements=movements, products=products, locations=locations, label="Move Item")

@movements_bp.route("/movements/new", methods=['GET', 'POST'])
def new_movement():
    form = MovementForm()

    # Auto fill Product, Location fields on the form
    get_choices(form)

    # Declaring variables
    from_location = convert_location_id_to_name(form.from_location.data)
    to_location = convert_location_id_to_name(form.to_location.data)
    product_id = form.product_id.data
    qty = form.qty.data

    # Check if data already exist
    existing_movement = movement_exist(product_id, from_location, to_location)
    existing_prd_in_from_location = movement_exist(product_id, "", from_location)
    existing_prd_in_to_location = movement_exist(product_id, "", to_location)

    if form.validate_on_submit():
        error = error_conditions(from_location, to_location, qty, existing_prd_in_from_location, existing_prd_in_to_location, 'new', 0)
        if(error != 'No error'):
            return redirect(url_for('movements_bp.new_movement'))
        else:
            #qty++ in to_location
            if existing_movement and existing_movement.from_location == "" and existing_movement.to_location != "":
                existing_prd_in_to_location.qty = existing_prd_in_to_location.qty + qty

            #qty-- in from_location
            elif existing_movement and existing_movement.from_location != "" and existing_movement.to_location == "":
                existing_prd_in_from_location.qty = existing_prd_in_from_location.qty - qty

            #qty++ in to_location and qty-- in from_location
            elif (existing_movement and existing_movement.from_location != "" and existing_movement.to_location != "" ) or (existing_prd_in_to_location and existing_prd_in_from_location):
                existing_prd_in_to_location.qty = existing_prd_in_to_location.qty + qty
                existing_prd_in_from_location.qty = existing_prd_in_from_location.qty - qty

            #decrement from from_location and then create to_location
            elif existing_prd_in_from_location and not existing_prd_in_to_location:
                existing_prd_in_from_location.qty = existing_prd_in_from_location.qty - qty
                if to_location != "":
                    product_to = Movement(from_location="", to_location=to_location, product_id=product_id, qty=qty,timestamp=date_convertion())
                    db.session.add(product_to)
                    db.session.commit()

            else:
                movement = Movement(from_location=from_location, to_location=to_location, product_id=product_id, qty=qty,timestamp=date_convertion())
                db.session.add(movement)

        if from_location != "" and to_location != "":
            movement = Movement(from_location=from_location, to_location=to_location, product_id=product_id, qty=qty,timestamp=date_convertion())
            db.session.add(movement)

        static_movement = StaticMovement(from_location=from_location, to_location=to_location, product_id=product_id, qty=qty,timestamp=date_convertion())
        db.session.add(static_movement)
        db.session.commit()
        
        flash('Your product movement is successfully added in the product movement list!', 'green')
        return redirect(url_for('movements_bp.movements'))
    return render_template('create_movement.html', form=form, legend='New Product Movement', title='Move Product', label='Movement')

@movements_bp.route("/movement/<int:movement_id>")
@movements_bp.route("/movement/<int:movement_id>/<int:qty>")
def movement(movement_id, qty=None):
    movement = StaticMovement.query.get_or_404(movement_id)
    products = Product.query
    return render_template('movement.html', title='Update Moved Product', movement=movement, products=products, qty=qty, label='Movement')

@movements_bp.route("/movement/<int:movement_id>/update", methods=['GET', 'POST'])
def update_movement(movement_id):
    
    static_movement = StaticMovement.query.get_or_404(movement_id)
    form = MovementForm()
    
    # Auto fill Product, Location fields on the form
    get_choices(form)

    # Declaring variables
    from_location = convert_location_id_to_name(form.from_location.data)
    to_location = convert_location_id_to_name(form.to_location.data)
    product_id = form.product_id.data
    qty = form.qty.data

    # Check if data already exist
    existing_movement = movement_exist(product_id, from_location, to_location)
    existing_prd_in_from_location = movement_exist(product_id, "", from_location)
    existing_prd_in_to_location = movement_exist(product_id, "", to_location)

    if form.validate_on_submit(): 
        error = error_conditions(from_location, to_location, qty, existing_prd_in_from_location, existing_prd_in_to_location, "update", static_movement.qty)
        if(error == 'No error'):
            #qty++ in to_location
            if existing_movement and existing_movement.from_location == "" and existing_movement.to_location != "":
                print(existing_prd_in_to_location.qty)
                print(qty)
                print(static_movement.qty)
                existing_prd_in_to_location.qty = existing_prd_in_to_location.qty + qty - static_movement.qty
                print(existing_prd_in_to_location.qty)

            #qty-- in from_location

inventory/products/__init__.py
#Comment

inventory/products/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from inventory import db
from inventory.products.forms import ProductForm, UpdateProductForm
from inventory.models import Product
from inventory.utils import save_picture

products_bp = Blueprint('products_bp', __name__)

# Product

@products_bp.route('/search_product')
def search_product():
    query = request.args.get('query')
    if not query:
        return products()
    searched_products = Product.query.filter(Product.product_name.contains(query)).all()
    return render_template('products.html', products=searched_products, title='Search Result', label='Product')

@products_bp.route('/products', methods=['GET', 'POST'])
def products():
    products = Product.query.order_by(Product.product_name).all()
    return render_template('products.html', products=products, title='Product', label='Add Product')

@products_bp.route('/products/new', methods=['GET', 'POST'])
def new_product():
    form = ProductForm()
    if form.validate_on_submit():
        if form.product_picture.data:
            picture_file = save_picture(form.product_picture.data)
        else:
            picture_file = 'default-cars.jpeg'
        product = Product(product_name=form.product_name.data, product_description=form.product_description.data, product_image_file=picture_file)
        db.session.add(product)
        db.session.commit()
        flash('Your product is successfully added in the product list!', 'green')
        return redirect(url_for('products_bp.products'))
    return render_template('create_product.html', form=form, title='Add New Product', label='Product')

@products_bp.route("/product/<int:product_id>")
def product(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('product.html', title='Update Product', product=product, label='Product')

@products_bp.route("/product/<int:product_id>/update", methods=['GET', 'POST'])
def update_product(product_id):
    product = Product.query.get_or_404(product_id)
    form = UpdateProductForm()

    if not product.product_name == form.product_name.data:
        form = ProductForm()

    if form.validate_on_submit():
        if form.product_picture.data:
            picture_file = save_picture(form.product_picture.data)
            product.product_image_file = picture_file
        product.product_description = form.product_description.data
        product.product_name = form.product_name.data
        db.session.commit()
        flash('Your product has been updated!', 'green')
        return redirect(url_for('products_bp.product', product_id=product.product_id))
    elif request.method == 'GET':
        form.product_name.data = product.product_name
        form.product_description.data = product.product_description
    form.submit.label.text = 'Update Product'
    return render_template('create_product.html', title='Update Product', form=form, label='Product')

inventory/templates/create_location.html
{% extends "layout.html" %}
{% block content %}
<div class="container leading-loose mx-auto flex justify-center mt-8">
  <form class="max-w-xl m-4 p-10 bg-white rounded shadow-xl flex-grow" method="POST" enctype="multipart/form-data">
    {{  form.hidden_tag() }}
    <p class="text-gray-800 font-medium text-xl">{{ title }}</p>
    <div class="locationName">
      <label class="block text-sm text-gray-600" for="location_name">{{ form.location_name.label }}</label>
        {% if form.location_name.errors %}
        {{ form.location_name(class="w-full px-5 py-1 border-2 border-red-400 text-red-700 bg-gray-200 rounded", placeholder="Location Name", id="location_name", required="", type="text") }} 
            <div class="text-red-600">
                {% for error in form.location_name.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>  
        {% else %}
          {{ form.location_name(class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded", placeholder="Location Name", id="location_name", required="", type="text") }}
        {% endif %}
    </div>
    <div class="locationDesc">
      <label class="block text-sm text-gray-600" for="location_description">Description</label>
      {{ form.location_description(class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded",  rows="3", placeholder="Add some description.....") }}
    </div>
    <div class="locationPictureUpload">
        <label class="block text-sm text-gray-600" for="location_name">{{ form.location_picture.label() }}</label>
        <label class="w-40 flex items-center px-4 py-3 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-indigo-100">
            <svg class="w-4 h-4" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
            </svg>
            <span class="ml-2 text-xs leading-normal">Select a file</span>
            {{ form.location_picture(class="hidden", type="file") }}
        </label>
        {% if form.location_picture.errors %}
            {% for error in form.location_picture.errors %}
                <span class="text-red-600">{{ error }}</span></br>
            {% endfor %}
        {% endif %}
    </div>
    <div class="mt-4">
      {{ form.submit(class="px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded", type="submit") }}
    </div>
  </form>
</div>
{% endblock content %}

inventory/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>Home Page</h1>
{% endblock content %}

inventory/templates/location.html
{% extends "layout.html" %}
{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
        <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
            <img alt="car" class="object-cover object-center w-full h-full block" src="{{ url_for('static', filename='img/' + location.location_image_file) }}">
        </div>
        <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                {{ location.location_name }}
            </h1>
            <p class="mb-8 leading-relaxed">
                {% if not location.location_description %}
                    This is a default description for location, please update the location with a brief description.
                {% else %}
                    {{ location.location_description }}
                {% endif %}
            </p>
            <div class="flex justify-center">
                <a href="{{ url_for('locations_bp.update_location', location_id=location.location_id) }}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg cursor-pointer">Edit</a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

inventory/templates/movement.html
{% extends "layout.html" %}
{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto px-12 py-24 md:flex-row flex-col items-center">
        <a class="flex w-full bg-white mx-3 mb-1 rounded py-2 md:p-4" href="{{ url_for('movements_bp.movement', movement_id=movement.movement_id) }}">
            <div class="self-center p-2 sm:py-4 sm:p-8 md:pl-4 flex-row border-indigo-200">
                <div class="mb-1 font-semibold text-xs sm:text-sm">{{ movement.timestamp.strftime('%d %b, %y') }}</div>
                <div class="text-gray-500 font-bold text-xs ">{{ movement.timestamp.strftime('%H:%M %p') }}</div>
            </div>
            <div class="border-r-2 border-indigo-200 mr-3 sm:mr-0 my-2 md:my-0"></div>
            <div class="flex-1 sm:py-4 sm:px-6">
                <div class= "text-gray-600 py-1 sm:py-2 sm:flex">
                    <div class="mx-2 sm:mx-0 p-2 sm:p-3 border-b-2 border-indigo-200 sm:border-b-0">
                        <span class="rounded text-white bg-indigo-400 py-1 px-2 text-xs sm:text-sm font-bold mr-2">{% if qty == None %}{{ movement.qty }}{% else %}{{ qty }}{% endif %}</span>
                        <span class="font-semibold text-sm sm:text-lg">{{ products.get(movement.product_id).product_name }}</span>
                    </div>
                    <div class="border-r-2 ml-4 border-indigo-200 mr-3 hidden sm:block sm:-my-4 md:-my-6 {% if not movement.from_location or not movement.to_location %} sm:hidden {% endif %}"></div>
                    <div class="flex p-3 {% if not movement.to_location %} flex-row-reverse float-left {% endif %}">
                        <span class="font-semibold text-sm sm:text-lg mr-2 md:ml-2 md:mr-6 {% if not movement.from_location %} hidden {% endif %}">{{ movement.from_location }}  
                        </span>
                        <span class="inline-block {% if not movement.to_location %} mr-4 {% endif %}">
                            <svg class="fill-current text-indigo-400 h-6 w-6 sm:h-8 sm:w-8" {% if not movement.to_location %} transform="rotate(180)" {% endif %}  viewBox="0 1 24 24">
                                <path d="M16 7.328V4l8 8-8 8v-3.328L0 12z"/>
                            </svg>
                        </span>
                        <span class="font-semibold text-sm sm:text-lg mx-2 md:ml-6 {% if not movement.to_location %} hidden {% endif %}">{{ movement.to_location }}</span>
                    </div>
                </div>
            </div>
        </a>
        <div class="flex justify-between ml-3 -mr-3 mt-2">
            <div class="p-2 text-gray-600">
                {% if qty == None %}{{ movement.qty }}{% else %}{{ qty }}{% endif %} {{ products.get(movement.product_id).product_name }} was 
                {% if movement.from_location and movement.to_location %}  
                    moved from {{ movement.from_location }} location to {{ movement.to_location }} location.
                {% elif not movement.from_location %}
                    added into {{ movement.to_location }} location.
                {% elif not movement.to_location %}
                    removed from {{ movement.from_location }} location.
                {% endif %}
            </div>
            <div class="flex content-end">
                <a href="{{ url_for('movements_bp.update_movement', movement_id=movement.movement_id) }}" class="inline-flex self-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg cursor-pointer">Edit</a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

inventory/templates/movements.html
{% extends "layout.html" %}
{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-8 lg:px-24 py-8 mx-auto flex flex-wrap -m-4">
            {% if not movements%}
                <div class="px-4 sm:px-8 lg:px-0 w-full">
                    <h2>No items found!! Please add movement by clicking on Move Item button.</h2>
                </div>
            {% else %}
                {% for movement in movements %}
                    <a class="flex w-full bg-white mx-3 mb-3 rounded py-2 md:p-4" href="{{ url_for('movements_bp.movement', movement_id=movement.movement_id, qty=movement.qty) }}">
                        <div class="self-center p-2 sm:py-4 sm:p-8 md:pl-4 flex-row border-indigo-200">
                            <div class="mb-1 font-semibold text-xs sm:text-sm">{{ movement.timestamp.strftime('%d %b, %y') }}</div>
                            <div class="text-gray-500 font-bold text-xs ">{{ movement.timestamp.strftime('%H:%M %p') }}</div>
                        </div>
                        <div class="border-r-2 border-indigo-200 mr-3 sm:mr-0 my-2 md:my-0"></div>
                        <div class="flex-1 sm:py-4 sm:px-6">
                            <div class= "text-gray-600 py-1 sm:py-2 sm:flex">
                                <div class="mx-2 sm:mx-0 p-2 sm:p-3 border-b-2 border-indigo-200 sm:border-b-0">
                                    <span class="rounded text-white bg-indigo-400 py-1 px-2 text-xs sm:text-sm font-bold mr-2">{{ movement.qty }}</span>
                                    <span class="font-semibold text-sm sm:text-lg">{{ products.get(movement.product_id).product_name }}</span>
                                </div>
                                <div class="border-r-2 ml-4 border-indigo-200 mr-3 hidden sm:block sm:-my-4 md:-my-6 {% if not movement.from_location or not movement.to_location %} sm:hidden {% endif %}"></div>
                                <div class="flex p-3 {% if not movement.to_location %} flex-row-reverse float-left {% endif %}">
                                    <span class="font-semibold text-sm sm:text-lg mr-2 md:ml-2 md:mr-6 {% if not movement.from_location %} hidden {% endif %}">{{ movement.from_location }}  
                                    </span>
                                    <span class="inline-block {% if not movement.to_location %} mr-4 {% endif %}">
                                        <svg class="fill-current text-indigo-400 h-6 w-6 sm:h-8 sm:w-8" {% if not movement.to_location %} transform="rotate(180)" {% endif %}  viewBox="0 1 24 24">
                                            <path d="M16 7.328V4l8 8-8 8v-3.328L0 12z"/>
                                        </svg>
                                    </span>
                                    <span class="font-semibold text-sm sm:text-lg mx-2 md:ml-6 {% if not movement.to_location %} hidden {% endif %}">{{ movement.to_location }}</span>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock content %}

inventory/templates/product.html
{% extends "layout.html" %}
{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
        <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
            <img alt="car" class="object-cover object-center w-full h-full block" src="{{ url_for('static', filename='img/' + product.product_image_file) }}">
        </div>
        <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                {{ product.product_name }}
            </h1>
                <p class="mb-8 leading-relaxed">
                    {% if not product.product_description %}
                        This is a default description for product, please update the product with a brief description.
                    {% else %}
                        {{ product.product_description }}
                    {% endif %}
                </p>
            <div class="flex justify-center">
                <a href="{{ url_for('products_bp.update_product', product_id=product.product_id) }}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg cursor-pointer">Edit</a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}